# Generated by Django 5.2.8 on 2026-08-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_payment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('product', 'Mahsulot (Product)'), ('discount', 'Kurs uchun chegirma (Course Discount)')], default='product', max_length=20)),
                ('points_cost', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Percentage discount for courses (e.g. 10)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='market/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to='users.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='students.marketitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
