# Generated by Django 5.2.8 on 2026-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_test_testquestion_testoption_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_interval_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
