# Generated by Django 5.2.8 on 2026-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_test_testquestion_testoption_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_interval_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Savollar orasidagi interval vaqti (sekundlarda), 0 = cheklovsiz'),
        ),
    ]
