# Generated by Django 5.2.8 on 2026-08-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_test_question_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_questions/'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
