# Generated by Django 5.2.8 on 2026-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='performance_type',
            field=models.CharField(choices=[('classwork', 'Classwork'), ('homework', 'Homework'), ('exam', 'Exam')], default='classwork', max_length=12),
        ),
    ]
